import { logger } from '../core/logger.js';

const PRICING = { '1Hour': 0.50, '1Day': 1.00, '7Day': 3.00, '30Days': 5.00, default: 10.00 };
const DAY_MS = 86_400_000; const HOUR_MS = 3_600_000;

class FinancialController {
  constructor(deps = {}) { this.database = deps.database || deps.db; this.mastercard = deps.mastercard || null; this.pricing = { ...PRICING, ...(deps.pricing || {}) }; }
  _price(plan) { const key = Object.keys(this.pricing).find((k) => k.toLowerCase() === String(plan || '').toLowerCase()); return this.pricing[key] ?? this.pricing.default; }
  async getRevenueReport() { if (!this.database) return { error: 'Database not available' }; const vouchers = await this.database.getRecentVouchers(10000); const start = new Date(new Date().toDateString()).getTime(); let total = 0, today = 0, pending = 0; const plans = {}; for (const v of vouchers) { const price = this._price(v.plan); total += price; if (new Date(v.createdAt).getTime() >= start) today += price; if (!v.used) pending += price; plans[v.plan] = (plans[v.plan] || 0) + 1; } return { currency: 'USD', grossRevenue: total.toFixed(2), todayRevenue: today.toFixed(2), potentialRevenue: pending.toFixed(2), topPlan: Object.entries(plans).sort((a, b) => b[1] - a[1])[0]?.[0] || 'N/A', totalVouchers: vouchers.length }; }
  async getTrends() { if (!this.database) return { error: 'Database not available' }; const vouchers = await this.database.getRecentVouchers(10000); const now = Date.now(); const days = Array.from({ length: 7 }, (_, i) => { const start = now - (6 - i) * DAY_MS, end = start + DAY_MS; const label = new Date(start).toISOString().slice(5, 10); const created = vouchers.filter((v) => { const t = new Date(v.createdAt).getTime(); return t >= start && t < end; }); return { label, count: created.length, revenue: created.reduce((s, v) => s + this._price(v.plan), 0).toFixed(2) }; }); const hourly = Array.from({ length: 24 }, (_, h) => { const start = now - (23 - h) * HOUR_MS, end = start + HOUR_MS; return vouchers.filter((v) => { const t = new Date(v.createdAt).getTime(); return t >= start && t < end; }).length; }); const planMix = {}; vouchers.forEach((v) => { planMix[v.plan] = (planMix[v.plan] || 0) + 1; }); const churnAtRisk = vouchers.filter((v) => { if (v.used || !v.expiresAt || !v.createdAt) return false; const window = new Date(v.expiresAt).getTime() - new Date(v.createdAt).getTime(); return window > 0 && (now - new Date(v.createdAt).getTime()) / window > 0.9; }).length; const thisWeek = days.slice(4).reduce((s, d) => s + Number(d.revenue), 0), lastWeek = days.slice(0, 3).reduce((s, d) => s + Number(d.revenue), 0); return { days, hourly, planMix, churnAtRisk, weekOnWeekGrowth: lastWeek > 0 ? (((thisWeek - lastWeek) / lastWeek) * 100).toFixed(1) : null }; }
  async verifyPayment(paymentId) { if (!this.mastercard) { logger.warn('FinancialController: Mastercard service not configured'); return { status: 'unknown', error: 'Service unavailable' }; } return this.mastercard.getPaymentStatus(paymentId); }
  async auditTrail(limit = 100) { return this.database ? this.database.getAuditLog(limit) : []; }
  async generateInvoice(data) { logger.info('FinancialController: generating invoice', data); return { id: `INV-${Date.now()}`, status: 'generated', timestamp: new Date().toISOString() }; }
}
export default FinancialController;
