import crypto from 'node:crypto';
import { EventEmitter } from 'node:events';
import { logger } from '../../core/logger.js';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);

class UniversalBilling extends EventEmitter {
  constructor(config = {}) { super(); this.db = config.database || null; this.mikrotik = config.mikrotik || null; this.resourceType = config.resourceType || 'network'; this.config = config; this.provider = String(config.paymentProvider || process.env.PAYMENT_PROVIDER || 'none').toLowerCase(); this._client = null; }
  async createPaymentLink({ plan, label, amount, currency }) { const cfg = this.config.payments || this._readConfigFile(); const amt = amount || this._getPlanAmount(plan, cfg); const cur = (currency || cfg?.currency || process.env.PAYMENT_CURRENCY || 'USD').toUpperCase(); const lbl = label || plan || 'AgentOS Access'; switch (this.provider) { case 'stripe': return this._stripeLink(plan, amt, cur, lbl, cfg); case 'pesapay': return this._pesapayLink(plan, amt, cur, lbl, cfg); case 'mpesa': return this._mpesaLink(plan, amt, cur, lbl, cfg); case 'mastercard': case 'peach': return this._peachLink(plan, amt, cur, lbl, cfg); case 'mastercard-a2a': case 'a2a': return this._mastercardA2ALink(plan, amt, cur, lbl, cfg); case 'webhook': return this._webhookLink(plan, amt, cur, lbl, cfg); default: throw new Error(`No payment provider configured (provider="${this.provider}")`); } }
  async verifyPayment(reference) { const cfg = this.config.payments || this._readConfigFile(); switch (this.provider) { case 'stripe': return this._stripeVerify(reference, cfg); case 'pesapay': return this._pesapayVerify(reference, cfg); case 'mpesa': return this._mpesaVerify(reference, cfg); case 'mastercard': case 'peach': return this._peachVerify(reference, cfg); case 'mastercard-a2a': case 'a2a': return this._mastercardA2AVerify(reference, cfg); case 'webhook': return { paid: true, reference }; default: return { paid: false, reason: 'no_provider' }; } }
  async _stripeLink(plan, amount, currency, label, cfg) { const key = cfg?.credentials?.secretKey || process.env.STRIPE_SECRET_KEY; if (!key) throw new Error('Stripe secret key not configured'); const stripe = require('stripe')(key); const reference = `agentos-${plan}-${Date.now()}`; const session = await stripe.checkout.sessions.create({ payment_method_types: ['card'], line_items: [{ price_data: { currency: currency.toLowerCase(), product_data: { name: `AgentOS — ${label}` }, unit_amount: Math.round(amount * 100) }, quantity: 1 }], mode: 'payment', success_url: cfg?.credentials?.successUrl || process.env.STRIPE_SUCCESS_URL || 'http://localhost:3000/success?session={CHECKOUT_SESSION_ID}', cancel_url: cfg?.credentials?.cancelUrl || process.env.STRIPE_CANCEL_URL || 'http://localhost:3000/cancel', client_reference_id: reference, metadata: { plan, reference } }); return session.url; }
  async _stripeVerify(sessionId, cfg) { const key = cfg?.credentials?.secretKey || process.env.STRIPE_SECRET_KEY; if (!key) return { paid: false, reason: 'no_key' }; const stripe = require('stripe')(key); const session = await stripe.checkout.sessions.retrieve(sessionId); return { paid: session.payment_status === 'paid', reference: sessionId, plan: session.metadata?.plan }; }
  async _pesapayLink(plan, amount, currency, label, cfg) { const axios = require('axios'); const apiKey = cfg?.credentials?.apiKey || process.env.PESAPAY_API_KEY; const merchantId = cfg?.credentials?.merchantId || process.env.PESAPAY_MERCHANT_ID; const baseUrl = cfg?.credentials?.baseUrl || process.env.PESAPAY_BASE_URL || 'https://www.pesapay.co.za'; if (!apiKey || !merchantId) throw new Error('PesaPay API key / merchant ID not configured'); const reference = `AGT-${plan}-${Date.now()}`; const response = await axios.post(`${baseUrl}/api/paynow/v2/payment/initiate`, { merchantId, merchantReference: reference, amount: amount.toFixed(2), currency, description: `AgentOS — ${label}`, redirectUrl: process.env.PESAPAY_REDIRECT_URL || `${baseUrl}/return` }, { headers: { Authorization: `Bearer ${apiKey}`, 'Content-Type': 'application/json' } }); if (!response.data?.redirectUrl) throw new Error(`PesaPay did not return a redirect URL`); return response.data.redirectUrl; }
  async _pesapayVerify(reference, cfg) { const axios = require('axios'); const apiKey = cfg?.credentials?.apiKey || process.env.PESAPAY_API_KEY; const baseUrl = cfg?.credentials?.baseUrl || process.env.PESAPAY_BASE_URL || 'https://www.pesapay.co.za'; const resp = await axios.get(`${baseUrl}/api/paynow/v2/payment/query/${reference}`, { headers: { Authorization: `Bearer ${apiKey}` } }); return { paid: resp.data?.status?.toLowerCase() === 'paid', reference, plan: resp.data?.description }; }
  async _mpesaLink(plan, amount, currency, label, cfg) { return this._mpesaInitiateSTK(null, amount, plan, cfg, process.env.MPESA_PROVIDER || 'safaricom'); }
  async _mpesaInitiateSTK(phone, amount, plan, cfg, providerOverride) { const { MobileMoney } = require('../../services/mobile-money'); const mm = new MobileMoney(); const provider = providerOverride || cfg?.credentials?.provider || process.env.MPESA_PROVIDER || 'safaricom'; if (!phone) return `Mobile Money Payment: ${amount} (${plan}) via ${provider}. Use /pay ${plan} <phone> to receive a payment request.`; const result = await mm.initiate(provider, phone, amount, `AGT-${plan}`); logger.info(`[Billing] STK Push sent via ${provider} to ${phone}`); return result; }
  async _mpesaVerify(checkoutRequestId, cfg) { const { MobileMoney } = require('../../services/mobile-money'); const mm = new MobileMoney(); const provider = cfg?.credentials?.provider || process.env.MPESA_PROVIDER || 'safaricom'; try { const result = await mm.verify(provider, checkoutRequestId); return { paid: result.paid, reference: checkoutRequestId, ...result }; } catch (error) { logger.error('[Billing] M-Pesa verification failed:', error.message); return { paid: false, reason: 'api_error', error: error.message }; } }
  async _peachLink(plan, amount, currency, label, cfg) { const axios = require('axios'); const apiKey = cfg?.credentials?.apiKey || process.env.PEACH_API_KEY; const entityId = cfg?.credentials?.entityId || process.env.PEACH_ENTITY_ID; const baseUrl = cfg?.credentials?.baseUrl || process.env.PEACH_BASE_URL || 'https://testsecure.peachpayments.com'; if (!apiKey || !entityId) throw new Error('Peach Payments credentials not configured'); const reference = `AGT-${plan}-${Date.now()}`; const params = new URLSearchParams({ 'authentication.userId': entityId, 'authentication.password': apiKey, 'authentication.entityId': entityId, amount: amount.toFixed(2), currency, paymentType: 'DB', merchantTransactionId: reference, descriptor: `AgentOS ${label}` }); const resp = await axios.post(`${baseUrl}/v1/checkouts`, params.toString(), { headers: { 'Content-Type': 'application/x-www-form-urlencoded' } }); return `${baseUrl}/v1/paymentWidgets.js?checkoutId=${resp.data?.id}`; }
  async _peachVerify(checkoutId, cfg) { const axios = require('axios'); const apiKey = cfg?.credentials?.apiKey || process.env.PEACH_API_KEY; const entityId = cfg?.credentials?.entityId || process.env.PEACH_ENTITY_ID; const baseUrl = cfg?.credentials?.baseUrl || process.env.PEACH_BASE_URL || 'https://testsecure.peachpayments.com'; if (!apiKey || !checkoutId) return { paid: false, reason: 'missing_id' }; try { const resp = await axios.get(`${baseUrl}/v1/checkouts/${checkoutId}/payment`, { params: { entityId }, headers: { Authorization: `Bearer ${apiKey}` } }); const code = resp.data?.result?.code; return { paid: /^(000\.000\.|000\.100\.|000\.400\.)/.test(code), reference: checkoutId, status: resp.data?.result?.description, code }; } catch { return { paid: false, reason: 'api_error' }; } }
  async _mastercardA2ALink(plan, amount, currency, label, cfg) { const MastercardA2A = require('../../services/mastercardA2A'); const service = new MastercardA2A(); const code = this.generateSecureCode(); const recipientAccount = cfg?.credentials?.recipientAccount || process.env.MASTERCARD_RECIPIENT_ACCOUNT || 'ZW1234567890'; const recipientBankCode = cfg?.credentials?.recipientBankCode || process.env.MASTERCARD_RECIPIENT_BANK || 'BR3EZE'; const result = await service.processVoucherPurchase({ plan, code }, { amount, recipientAccount, recipientBankCode }); if (!result.success) throw new Error(`Mastercard A2A initiation failed`); return result.transactionRef || result.paymentId; }
  async _mastercardA2AVerify(paymentId) { const MastercardA2A = require('../../services/mastercardA2A'); const status = await new MastercardA2A().getPaymentStatus(paymentId); return { paid: status.success && status.status === 'COMPLETED', reference: paymentId, plan: status.raw?.metadata?.plan }; }
  async _webhookLink(plan, amount, currency, label, cfg) { const callbackUrl = cfg?.credentials?.callbackUrl || process.env.PAYMENT_WEBHOOK_URL; if (!callbackUrl) throw new Error('Webhook payment URL not configured'); return `${callbackUrl}?${new URLSearchParams({ plan, amount, currency, label, reference: `AGT-${plan}-${Date.now()}` })}`; }
  async createVoucher(params = {}) { const { type = 'access', value, resourceId, metadata = {} } = params; const code = this.generateSecureCode(); const voucher = { code, type, value, resourceId, status: 'active', createdAt: new Date().toISOString(), expiresAt: this.calculateExpiry(type, value), metadata: { ...metadata, createdBy: metadata.createdBy || 'system', domain: this.resourceType }, redemption: { used: false, usedAt: null, usedBy: null, remainingValue: value } }; if (this.db) await this.db.saveVoucher(voucher); if (metadata.generateQR) { const QRCode = require('qrcode'); voucher.qrCode = await QRCode.toDataURL(JSON.stringify({ code, type: this.resourceType, resource: resourceId })); } return voucher; }
  async redeemVoucher(code, redemptionData = {}) { if (!this.db) throw new Error('Database not initialized'); const result = await this.db.redeemVoucher(code, redemptionData); if (!result.success) throw new Error(result.error || 'Voucher redemption failed'); const voucher = result.voucher; return { success: true, voucher: { code: voucher.code, type: voucher.type || 'access', value: voucher.value, expiresAt: voucher.expiresAt }, access: await this.provisionAccess(voucher, redemptionData) }; }
  async provisionAccess(voucher) { const provisioners = { network: async () => ({ username: voucher.code, password: voucher.code, profile: 'voucher' }), compute: async () => ({ credits: voucher.value, instanceToken: this.generateSecureCode() }), api: async () => ({ apiKey: this.generateSecureCode(), rateLimit: voucher.value }) }; return (provisioners[this.resourceType] || provisioners.network)(); }
  async validateCode(code) { if (!this.db) return { valid: false, reason: 'no_database' }; const voucher = await this.db.getVoucher(code); if (!voucher) return { valid: false, reason: 'not_found' }; if (voucher.redemption?.used && voucher.type !== 'credits') return { valid: false, reason: 'used' }; if (voucher.expiresAt && new Date() > new Date(voucher.expiresAt)) return { valid: false, reason: 'expired' }; return { valid: true, voucher }; }
  generateSecureCode() { const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; const bytes = crypto.randomBytes(8); let code = ''; for (let i = 0; i < 8; i++) code += chars[bytes[i] % chars.length]; const checksum = code.split('').reduce((a, b) => a + b.charCodeAt(0), 0) % 10; return `${code}${checksum}`; }
  calculateExpiry(planOrType, legacyValue) { const now = new Date(); if (planOrType && typeof planOrType === 'object') { const { durationUnit, durationValue } = planOrType; if (!durationUnit || durationValue == null) return null; const v = Number(durationValue) || 1; if (durationUnit === 'hours') now.setHours(now.getHours() + v); else if (durationUnit === 'days') now.setDate(now.getDate() + v); else if (durationUnit === 'weeks') now.setDate(now.getDate() + v * 7); else if (durationUnit === 'months') now.setMonth(now.getMonth() + v); else now.setDate(now.getDate() + 1); return now.toISOString(); } const value = Number(legacyValue) || 1; if (planOrType === 'time' || planOrType === '1h') now.setHours(now.getHours() + value); else if (planOrType === 'day' || planOrType === '1d') now.setDate(now.getDate() + value); else if (planOrType === 'week' || planOrType === '1w') now.setDate(now.getDate() + 7 * value); else if (planOrType === 'month' || planOrType === '1m') now.setMonth(now.getMonth() + value); else now.setDate(now.getDate() + 1); return now.toISOString(); }
  _getPlanAmount(planId, cfg) { const plans = Array.isArray(cfg?.plans) ? cfg.plans : Object.values(cfg?.plans || {}); const found = plans.find((p) => p.name === planId || p.mikrotikProfile === planId || p.id === planId); return found?.price || Number(process.env.PAYMENT_DEFAULT_AMOUNT) || 10; }
  _readConfigFile() { try { const { getConfig } = require('../../core/config.js'); return getConfig(); } catch { return null; } }
  async initiatePayment({ provider, phone, amount, plan }) { const cfg = this.config.payments || this._readConfigFile(); return this._mpesaInitiateSTK(phone, amount, plan, cfg, provider); }
}
export default UniversalBilling;
export { UniversalBilling };
