prefix = /etc/freeradius/3.0
exec_prefix = /usr
sysconfdir = /etc
localstatedir = /var
sbindir = ${exec_prefix}/sbin
logdir = /var/log/freeradius
run_dir = ${localstatedir}/run/freeradius
name = radiusd
max_request_time = 30
cleanup_delay = 5
max_requests = 4096
hostname_lookups = no
log {
  destination = files
  file = ${logdir}/radius.log
  stripped_names = no
  auth = yes
  auth_badpass = yes
  auth_goodpass = no
}
security {
  max_attributes = 200
  reject_delay = 1
  status_server = yes
}
thread pool {
  start_servers = 4
  max_servers = 32
  min_spare_servers = 2
  max_spare_servers = 8
  max_requests_per_server = 0
  max_queue_size = 65536
  cleanup_delay = 5
  max_requests = 0
}
$INCLUDE clients.conf
$INCLUDE proxy.conf
$INCLUDE sites-enabled/
