import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

/**
 * Renders an order as a one-page PDF via pdf-lib (no browser/HTML dependency).
 * "INVOICE" for orders still awaiting payment (cod); "RECEIPT" for orders
 * already settled (credits/card/cash) — the label is the only structural
 * difference, since both are the same underlying order document.
 */

const PAGE_WIDTH = 595.28; // A4
const PAGE_HEIGHT = 841.89;
const MARGIN = 50;

function money(n) { return `$${Number(n || 0).toFixed(2)}`; }

async function generateOrderPdf(order) {
    const doc = await PDFDocument.create();
    const page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    const font = await doc.embedFont(StandardFonts.Helvetica);
    const bold = await doc.embedFont(StandardFonts.HelveticaBold);

    const isPaid = order.status === 'paid';
    const docTitle = isPaid ? 'RECEIPT' : 'INVOICE';
    let y = PAGE_HEIGHT - MARGIN;

    const draw = (text, { x = MARGIN, size = 11, f = font, color = rgb(0, 0, 0) } = {}) => {
        page.drawText(String(text), { x, y, size, font: f, color });
    };
    const newline = (amount = 16) => { y -= amount; };

    draw('AgentOS Shop', { size: 20, f: bold });
    draw(docTitle, { x: PAGE_WIDTH - MARGIN - bold.widthOfTextAtSize(docTitle, 16), size: 16, f: bold, color: rgb(0, 0.4, 0.6) });
    newline(28);

    draw(`${order.invoiceNumber || order.orderId || order.id}`, { size: 11 });
    newline(16);
    draw(`Date: ${new Date(order.createdAt || Date.now()).toLocaleString()}`, { size: 10, color: rgb(0.4, 0.4, 0.4) });
    newline(14);
    draw(`Channel: ${order.channel || order.platform || 'web'}`, { size: 10, color: rgb(0.4, 0.4, 0.4) });
    newline(14);
    draw(`Payment: ${(order.payMethod || 'cod').toUpperCase()} — ${isPaid ? 'PAID' : 'DUE ON DELIVERY'}`, {
        size: 10, f: bold, color: isPaid ? rgb(0, 0.5, 0) : rgb(0.7, 0.4, 0),
    });
    newline(28);

    // Table header
    draw('Item', { size: 10, f: bold });
    draw('Qty', { x: PAGE_WIDTH - MARGIN - 180, size: 10, f: bold });
    draw('Price', { x: PAGE_WIDTH - MARGIN - 120, size: 10, f: bold });
    draw('Amount', { x: PAGE_WIDTH - MARGIN - 60, size: 10, f: bold });
    newline(10);
    page.drawLine({ start: { x: MARGIN, y }, end: { x: PAGE_WIDTH - MARGIN, y }, thickness: 0.5, color: rgb(0.7, 0.7, 0.7) });
    newline(16);

    const items = order.items || order.lineItems || [];
    for (const it of items) {
        const name = it.name || it.description || 'Item';
        const label = it.size ? `${name} (${it.size})` : name;
        const qty = it.qty || 1;
        const price = it.price ?? it.unitPrice ?? 0;
        draw(label.length > 40 ? label.slice(0, 37) + '...' : label, { size: 10 });
        draw(String(qty), { x: PAGE_WIDTH - MARGIN - 180, size: 10 });
        draw(money(price), { x: PAGE_WIDTH - MARGIN - 120, size: 10 });
        draw(money(price * qty), { x: PAGE_WIDTH - MARGIN - 60, size: 10 });
        newline(18);
    }

    newline(6);
    page.drawLine({ start: { x: MARGIN, y }, end: { x: PAGE_WIDTH - MARGIN, y }, thickness: 0.5, color: rgb(0.7, 0.7, 0.7) });
    newline(20);

    draw('Subtotal', { x: PAGE_WIDTH - MARGIN - 180, size: 10 });
    draw(money(order.subtotal), { x: PAGE_WIDTH - MARGIN - 60, size: 10 });
    newline(16);
    draw('Shipping', { x: PAGE_WIDTH - MARGIN - 180, size: 10 });
    draw(money(order.shipping), { x: PAGE_WIDTH - MARGIN - 60, size: 10 });
    newline(20);
    draw('TOTAL', { x: PAGE_WIDTH - MARGIN - 180, size: 12, f: bold });
    draw(money(order.total), { x: PAGE_WIDTH - MARGIN - 60, size: 12, f: bold });

    y = MARGIN;
    draw('Generated by AgentOS — thank you for your order.', { size: 8, color: rgb(0.5, 0.5, 0.5) });

    const bytes = await doc.save();
    return Buffer.from(bytes);
}

export { generateOrderPdf };
