import { defineSkill, defineTool } from '../skill.js';
import { scopeFrom, providerFrom, assertTenant, approvalOrProposal, providerCall } from './commerce-helpers.js';

const projectManagerSkill = defineSkill({
  name: 'project-manager',
  description: 'Tenant-scoped project governance, WBS coordination, handoffs, dependencies, risks, approvals, and closure.',
  specialist: 'project-manager',
  permissions: ['project:read'],
  ticketTypes: ['project-plan', 'wbs-package', 'specialist-handoff', 'dependency-check', 'project-risk', 'approval-request', 'milestone-update', 'project-close'],
  persona: 'Project Manager: coordinate specialist work packages and approvals without performing domain mutations owned by specialists.',
  tools: [
    defineTool({ name: 'project.create', description: 'Create a tenant-scoped project charter and baseline.', specialist: 'project-manager', permissions: ['project:write'], ticketTypes: ['project-plan'], risk: 'medium', parameters: { type: 'object', required: ['name', 'objective'], properties: { name: { type: 'string' }, objective: { type: 'string' }, sponsor: { type: 'string' }, budget: { type: 'object' } } }, outputSchema: {}, handler: async (args, context) => { const proposal = approvalOrProposal('project.create', args, context); if (proposal) return proposal; return assertTenant(await providerCall(providerFrom(context, 'projectManager'), 'createProject', { ...args, scope: scopeFrom(context) }), context.tenantId); } }),
    defineTool({ name: 'workpackage.create', description: 'Create a durable WBS package with one accountable specialist owner.', specialist: 'project-manager', permissions: ['wbs:write'], ticketTypes: ['wbs-package'], parameters: { type: 'object', required: ['projectId', 'packageId', 'owner', 'deliverable'], properties: { projectId: { type: 'string' }, packageId: { type: 'string' }, owner: { type: 'string' }, deliverable: { type: 'string' }, dependencies: { type: 'array' } } }, outputSchema: {}, handler: async (args, context) => assertTenant(await providerCall(providerFrom(context, 'projectManager'), 'createWorkPackage', { ...args, scope: scopeFrom(context) }), context.tenantId) }),
    defineTool({ name: 'workpackage.assign', description: 'Assign a role-bound work package to a specialist with explicit handoff scope.', specialist: 'project-manager', permissions: ['wbs:delegate'], ticketTypes: ['specialist-handoff'], risk: 'medium', parameters: { type: 'object', required: ['packageId', 'specialist', 'allowedScope'], properties: { packageId: { type: 'string' }, specialist: { type: 'string' }, allowedScope: { type: 'array' }, prohibitedScope: { type: 'array' } } }, outputSchema: {}, handler: async (args, context) => assertTenant(await providerCall(providerFrom(context, 'projectManager'), 'assignWorkPackage', { ...args, scope: scopeFrom(context) }), context.tenantId) }),
    defineTool({ name: 'dependency.check', description: 'Check package dependencies and critical-path readiness.', specialist: 'project-manager', permissions: ['wbs:read'], ticketTypes: ['dependency-check'], parameters: { type: 'object', required: ['projectId'], properties: { projectId: { type: 'string' }, packageId: { type: 'string' } } }, outputSchema: {}, handler: async (args, context) => assertTenant(await providerCall(providerFrom(context, 'projectManager'), 'checkDependencies', { ...args, scope: scopeFrom(context) }), context.tenantId) }),
    defineTool({ name: 'risk.record', description: 'Record a project risk with owner, impact, probability, response, and evidence.', specialist: 'project-manager', permissions: ['risk:write'], ticketTypes: ['project-risk'], parameters: { type: 'object', required: ['projectId', 'title', 'impact', 'probability', 'owner'], properties: { projectId: { type: 'string' }, title: { type: 'string' }, impact: { type: 'number', minimum: 1 }, probability: { type: 'number', minimum: 0, maximum: 1 }, owner: { type: 'string' }, response: { type: 'string' }, evidenceRefs: { type: 'array' } } }, outputSchema: {}, handler: async (args, context) => assertTenant(await providerCall(providerFrom(context, 'projectManager'), 'recordRisk', { ...args, scope: scopeFrom(context) }), context.tenantId) }),
    defineTool({ name: 'approval.request', description: 'Create an approval request for scope, budget, supplier, production, or external commitments.', specialist: 'project-manager', permissions: ['approval:write'], ticketTypes: ['approval-request'], risk: 'high', parameters: { type: 'object', required: ['projectId', 'action', 'argumentsHash'], properties: { projectId: { type: 'string' }, action: { type: 'string' }, argumentsHash: { type: 'string' }, expiresAt: { type: 'string' }, approver: { type: 'string' } } }, outputSchema: {}, handler: async (args, context) => assertTenant(await providerCall(providerFrom(context, 'projectManager'), 'requestApproval', { ...args, scope: scopeFrom(context) }), context.tenantId) }),
    defineTool({ name: 'milestone.update', description: 'Update a milestone from accepted activity evidence.', specialist: 'project-manager', permissions: ['wbs:write'], ticketTypes: ['milestone-update'], parameters: { type: 'object', required: ['projectId', 'milestoneId', 'status', 'evidenceRefs'], properties: { projectId: { type: 'string' }, milestoneId: { type: 'string' }, status: { type: 'string' }, evidenceRefs: { type: 'array' } } }, outputSchema: {}, handler: async (args, context) => assertTenant(await providerCall(providerFrom(context, 'projectManager'), 'updateMilestone', { ...args, scope: scopeFrom(context) }), context.tenantId) }),
    defineTool({ name: 'project.close', description: 'Propose or close a project only after reconciliation, acceptance, and evidence checks.', specialist: 'project-manager', permissions: ['project:write'], ticketTypes: ['project-close'], risk: 'high', parameters: { type: 'object', required: ['projectId', 'evidenceRefs'], properties: { projectId: { type: 'string' }, evidenceRefs: { type: 'array' }, acceptance: { type: 'object' } } }, outputSchema: {}, handler: async (args, context) => { const proposal = approvalOrProposal('project.close', args, context, { risk: 'high' }); if (proposal) return proposal; return assertTenant(await providerCall(providerFrom(context, 'projectManager'), 'closeProject', { ...args, scope: scopeFrom(context) }), context.tenantId); } }),
  ],
});

export { projectManagerSkill };
export default projectManagerSkill;
